-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.0.240.2
-- Module  Version: 5.4
-- Sun May 23 15:43:44 2021

-- parameterized module component declaration
component enc_sub_bytes_rom
    port (Address: in  std_logic_vector(7 downto 0); 
        OutClock: in  std_logic; OutClockEn: in  std_logic; 
        Reset: in  std_logic; Q: out  std_logic_vector(7 downto 0));
end component;

-- parameterized module component instance
__ : enc_sub_bytes_rom
    port map (Address(7 downto 0)=>__, OutClock=>__, OutClockEn=>__, 
        Reset=>__, Q(7 downto 0)=>__);
