-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2
-- Module  Version: 2.8
--C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n lut_rom_reg -lang vhdl -synth lse -bus_exp 7 -bb -arch xo2c00 -type rom -addr_width 8 -num_rows 256 -data_width 8 -outdata REGISTERED -memfile c:/users/leona/downloads/telegram desktop/mem_file_final/mem_file/te4_8bit.mem -memformat hex 

-- Sun May 23 16:15:34 2021

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO2;
use MACHXO2.components.all;
-- synopsys translate_on

entity lut_rom_reg is
    port (
        Address: in  std_logic_vector(7 downto 0); 
        OutClock: in  std_logic; 
        OutClockEn: in  std_logic; 
        Reset: in  std_logic; 
        Q: out  std_logic_vector(7 downto 0));
end lut_rom_reg;

architecture Structure of lut_rom_reg is

    -- internal signal declarations
    signal qdataout7_ffin: std_logic;
    signal qdataout6_ffin: std_logic;
    signal qdataout5_ffin: std_logic;
    signal qdataout4_ffin: std_logic;
    signal qdataout3_ffin: std_logic;
    signal qdataout2_ffin: std_logic;
    signal qdataout1_ffin: std_logic;
    signal qdataout0_ffin: std_logic;

    -- local component declarations
    component FD1P3DX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component ROM256X1A
        generic (INITVAL : in std_logic_vector(255 downto 0));
        port (AD7: in  std_logic; AD6: in  std_logic; AD5: in  std_logic; 
            AD4: in  std_logic; AD3: in  std_logic; AD2: in  std_logic; 
            AD1: in  std_logic; AD0: in  std_logic; DO0: out  std_logic);
    end component;
    attribute GSR : string; 
    attribute GSR of FF_7 : label is "ENABLED";
    attribute GSR of FF_6 : label is "ENABLED";
    attribute GSR of FF_5 : label is "ENABLED";
    attribute GSR of FF_4 : label is "ENABLED";
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    FF_7: FD1P3DX
        port map (D=>qdataout7_ffin, SP=>OutClockEn, CK=>OutClock, 
            CD=>Reset, Q=>Q(7));

    FF_6: FD1P3DX
        port map (D=>qdataout6_ffin, SP=>OutClockEn, CK=>OutClock, 
            CD=>Reset, Q=>Q(6));

    FF_5: FD1P3DX
        port map (D=>qdataout5_ffin, SP=>OutClockEn, CK=>OutClock, 
            CD=>Reset, Q=>Q(5));

    FF_4: FD1P3DX
        port map (D=>qdataout4_ffin, SP=>OutClockEn, CK=>OutClock, 
            CD=>Reset, Q=>Q(4));

    FF_3: FD1P3DX
        port map (D=>qdataout3_ffin, SP=>OutClockEn, CK=>OutClock, 
            CD=>Reset, Q=>Q(3));

    FF_2: FD1P3DX
        port map (D=>qdataout2_ffin, SP=>OutClockEn, CK=>OutClock, 
            CD=>Reset, Q=>Q(2));

    FF_1: FD1P3DX
        port map (D=>qdataout1_ffin, SP=>OutClockEn, CK=>OutClock, 
            CD=>Reset, Q=>Q(1));

    FF_0: FD1P3DX
        port map (D=>qdataout0_ffin, SP=>OutClockEn, CK=>OutClock, 
            CD=>Reset, Q=>Q(0));

    mem_0_7: ROM256X1A
        generic map (initval=> X"52379DE7B844E3E14CB3770196CA0329E7BAC28F866AAC825CAA2EC7BF977090")
        port map (AD7=>Address(7), AD6=>Address(6), AD5=>Address(5), 
            AD4=>Address(4), AD3=>Address(3), AD2=>Address(2), 
            AD1=>Address(1), AD0=>Address(0), DO0=>qdataout7_ffin);

    mem_0_6: ROM256X1A
        generic map (initval=> X"21E0B833255917823F6BCB91B30DB559E4851B3BF3AB2560980A3CC2C2FDB4FF")
        port map (AD7=>Address(7), AD6=>Address(6), AD5=>Address(5), 
            AD4=>Address(4), AD3=>Address(3), AD2=>Address(2), 
            AD1=>Address(1), AD0=>Address(0), DO0=>qdataout6_ffin);

    mem_0_5: ROM256X1A
        generic map (initval=> X"54B248130B4F256F7D8DCC4706319E086BC2AA4E0D787AA4F8045F7B6D98DD7F")
        port map (AD7=>Address(7), AD6=>Address(6), AD5=>Address(5), 
            AD4=>Address(4), AD3=>Address(3), AD2=>Address(2), 
            AD1=>Address(1), AD0=>Address(0), DO0=>qdataout5_ffin);

    mem_0_4: ROM256X1A
        generic map (initval=> X"F210A3AECE472E532624B286BC48ECB4F7F17A494CE30F58C2B0F97752B8B11E")
        port map (AD7=>Address(7), AD6=>Address(6), AD5=>Address(5), 
            AD4=>Address(4), AD3=>Address(3), AD2=>Address(2), 
            AD1=>Address(1), AD0=>Address(0), DO0=>qdataout4_ffin);

    mem_0_3: ROM256X1A
        generic map (initval=> X"4E9DDB76C892FB1BE9DA849CF6AC6C1B2568EA2EFFA8527D109020A2193D586A")
        port map (AD7=>Address(7), AD6=>Address(6), AD5=>Address(5), 
            AD4=>Address(4), AD3=>Address(3), AD2=>Address(2), 
            AD1=>Address(1), AD0=>Address(0), DO0=>qdataout3_ffin);

    mem_0_2: ROM256X1A
        generic map (initval=> X"AC39B6C0D6CE2EFC577D64E03B0C3FFB23A869A2A428C424A16387FB3B48B4C6")
        port map (AD7=>Address(7), AD6=>Address(6), AD5=>Address(5), 
            AD4=>Address(4), AD3=>Address(3), AD2=>Address(2), 
            AD1=>Address(1), AD0=>Address(0), DO0=>qdataout2_ffin);

    mem_0_1: ROM256X1A
        generic map (initval=> X"C870974094EAD8A96A450B2EF33486B4E61A4C5E97816F7A7BAE007D4C53FC7D")
        port map (AD7=>Address(7), AD6=>Address(6), AD5=>Address(5), 
            AD4=>Address(4), AD3=>Address(3), AD2=>Address(2), 
            AD1=>Address(1), AD0=>Address(0), DO0=>qdataout1_ffin);

    mem_0_0: ROM256X1A
        generic map (initval=> X"4F1EAD396F247A0410BDB210C006EAB568AB4BFA8ACB7A13B14EDE67096C6EED")
        port map (AD7=>Address(7), AD6=>Address(6), AD5=>Address(5), 
            AD4=>Address(4), AD3=>Address(3), AD2=>Address(2), 
            AD1=>Address(1), AD0=>Address(0), DO0=>qdataout0_ffin);

end Structure;

-- synopsys translate_off
library MACHXO2;
configuration Structure_CON of lut_rom_reg is
    for Structure
        for all:FD1P3DX use entity MACHXO2.FD1P3DX(V); end for;
        for all:ROM256X1A use entity MACHXO2.ROM256X1A(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
